### ISSUE TITLE
No valid streams were found. Please try again later!

### ISSUE THREAD

**Issue by ghost** [thundersquared/tikvidbot#10]
Currently I only get this error message. No valid streams were found. Please try again later!. It doesn't matter which video I take.

Can you help me?

**Comment by anatolinicolae** [comment]
Should be fixed in [v1.3.7](https://github.com/thundersquared/tikvidbot/releases/tag/1.3.7).

**Comment by Suyuimo** [comment]
I have delete the Docker Image and pulled it new but it is not working. How can I start it manually without docker? In the Console I see only:
`[Error: ENOENT: no such file or directory, unlink '/tmp/undefined.mp4'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/tmp/undefined.mp4'
}`
