### ISSUE TITLE
Error when tray service  Docker Version

### ISSUE THREAD

**Issue by hmunoz** [thundersquared/tikvidbot#15]
This a error Console with Docker version
[Error: ENOENT: no such file or directory, unlink '/tmp/undefined.mp4'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/tmp/undefined.mp4'
}

**Comment by anatolinicolae** [comment]
https://github.com/thundersquared/tikvidbot/issues/12#issuecomment-735380039
